version: '3.7'

services:
  PostgreSQL:
    image: postgres:12.0-alpine
    volumes:
      - ./data:/var/lib/postgres/data
    ports:
      - '5432:5432'
    environment:
       PGDATA: /var/lib/postgres/data
       POSTGRES_RANDOM_ROOT_PASSWORD: 'yes'
       POSTGRES_DATABSAE: app
       POSTGRES_USER: app
       POSTGRES_PASSWORD: pass123

  node-app:
    build: .
    image: node-app:1.0
    ports:
      - '9999:9999'
    volumes:
      - ./node:/var/lib/node_data
