version: '3.7'

services:
  postgresql:
    image: postgres:12.0-alpine
    ports:
      - '5432:5432'
    environment:
  #     PGDATA: /var/lib/postgresql/data
       POSTGRES_RANDOM_ROOT_PASSWORD: 'yes'
       POSTGRES_DATABASE: app
       POSTGRES_USER: app
       POSTGRES_PASSWORD: pass123
 #   volumes:
 #     - //c/docker/data:/var/lib/postgresql/data
